# Generated by Django 4.0.4 on 2022-06-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='topics',
        ),
    ]
