# Generated by Django 4.0.4 on 2022-06-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_topics'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='followers',
            field=models.ManyToManyField(blank=True, to='account.profile'),
        ),
    ]
